### ISSUE TITLE
App does not load after build

### ISSUE THREAD

**Issue by Ionaru** [mgechev/angular2-rollup-build#5]
Steps to reproduce:

- Clone repository  (`git clone <link> .`)
- Install dependencies (`npm i`)
- Build app (`npm run build_prod`)
- Run http-server (`npm run serve`)

The application will build successfully, but once navigated to the url with a browser, an error is given in the console and the app will not load.

The unminified error is:
```javascript
isFunction.js:4 
Uncaught TypeError: __extends is not a function
    at http://localhost:5557/dist/bundle.js:6137:9
    at http://localhost:5557/dist/bundle.js:6148:6
    at http://localhost:5557/dist/bundle.js:35696:2
```

This refers to this code block:
```javascript
var UnsubscriptionError = (function (_super) {
        __extends(UnsubscriptionError, _super);
        function UnsubscriptionError(errors) {
            _super.call(this);
            this.errors = errors;
            var err = Error.call(this, errors ?
                errors.length + " errors occurred during unsubscription:\n  " + errors.map(function (err, i) { return ((i + 1) + ") " + err.toString()); }).join('\n  ') : '');
            this.name = err.name = 'UnsubscriptionError';
            this.stack = err.stack;
            this.message = err.message;
        }
        return UnsubscriptionError;
    }(Error));
```

Why does this happen and how can we fix it?

**Comment by mgechev** [comment]
From what I can see there are missing TypeScript helper functions. Note that this **is a demo for the blog post, not a seed intended to be used in production**.

For production-quality starter I'd recommend you to use [angular-seed](https://github.com/mgechev/angular-seed).

**Comment by Ionaru** [comment]
Not very helpful if the demo for your post doesn't work though.
